# Generated by Django 5.2.4 on 2025-07-31 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="titel",
            new_name="title",
        ),
    ]
