# Generated by Django 5.2.4 on 2026-05-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0002_rename_titel_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name = "post",
            name = "author",
            field = models.ForeignKey(
                on_delete = django.db.models.deletion.CASCADE,
                related_name = "posts",
                to = settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name = "Like",
            fields = [
                (
                    "id",
                    models.BigAutoField(
                        auto_created = True,
                        primary_key = True,
                        serialize = False,
                        verbose_name = "ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.CASCADE,
                        to = "myapp.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.CASCADE,
                        to = settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options = {
                "unique_together": {("post", "user")},
            },
        ),
        migrations.AddField(
            model_name = "post",
            name = "liked_users",
            field = models.ManyToManyField(
                related_name = "liked_posts",
                through = "myapp.Like",
                to = settings.AUTH_USER_MODEL,
            ),
        ),
    ]
