# Generated by Django 5.2.4 on 2026-05-23 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0003_alter_post_author_like_post_liked_user"),
    ]

    operations = [
        migrations.CreateModel(
            name = "Comment",
            fields = [
                (
                    "id",
                    models.BigAutoField(
                        auto_created = True,
                        primary_key = True,
                        serialize = False,
                        verbose_name = "ID",
                    ),
                ),
                ("content", models.TextField(max_length = 500)),
                ("created_at", models.DateTimeField(auto_now_add = True)),
                ("updated_at", models.DateTimeField(auto_now = True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.CASCADE,
                        related_name = "comments",
                        to = settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.CASCADE,
                        related_name = "comments",
                        to = "myapp.post",
                    ),
                ),
            ],
            options = {
                "ordering": ["-created_at"],
            },
        ),
    ]
