# Generated by Django 5.2.4 on 2026-05-23 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name = "post",
            name = "created_at",
            field = models.DateTimeField(
                default = django.utils.timezone.now,
                editable = False,
            ),
        ),
    ]
